### ISSUE TITLE
Mais faites du pandoc bon sang

### ISSUE THREAD

**Issue by jilljenn** [eleurent/inria-beamer#1]
Du design à base d'ombres en 2019 ?

**Comment by eleurent** [comment]
Oui c'est l'ancien design, le [nouveau](https://intranet.inria.fr/Actualite/Mise-a-jour-de-la-charte-graphique-Inria-et-nouveaux-modeles) est plus moderne les sources latex sont dispo [ici](https://intranet.inria.fr/Vie-pratique/Informer-Communiquer/Identite-l-essentiel/Logo-utilisation-formats)

Je ne sais pas si c'est la peine de documenter celui-là du coup :thinking:
